Fix build with GCC 12 and musl (missing <ctime> include)
Fixes build errors like:
```
../../src/base/str.h:146:30: error: 'time_t' was not declared in this scope
  146 |     std::string rfc2822_time(time_t t);
```

Signed-off-by: Sam James <sam@gentoo.org>